ecommerce/src/carts/urls.py
from django.conf.urls import url


from .views import (
    cart_home, 
    cart_update,
    checkout_home,
    checkout_done_view
)

urlpatterns = [

    url(r'^$',cart_home, name="home"),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    
]

ecommerce/src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from accounts.views import login_page, register_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, about_page, contact_page
from carts.views import cart_detail_api_view



urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name="about"),
    url(r'^contact/$', contact_page, name="contact"),
    #important urls goes here
    url(r'^login/$', login_page, name="login"),
    url(r'^register/guest/$', guest_register_view, name="guest_register"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', register_page, name="register"),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^api/cart/$', cart_detail_api_view, name="api-cart"),
    url(r'^cart/', include("carts.urls", namespace="cart")),
    url(r'^bootstrap/$', TemplateView.as_view(template_name="bootstrap/example.html")),
    #url(r'^products/', include("products.urls")),
    url(r'^products/', include("products.urls", namespace="products")),
    url(r'^search/', include("search.urls", namespace="search")),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/src/products/urls.py
from django.conf.urls import url


from .views import (
    ProductListView, 
    ProductDetailSlugView,
    products_by_category,
)

urlpatterns = [
    # url(r'check/taglist/$', tag_list, name='tag-list'),

    # url(r'check/catlist/(?P<tag>[\w-]+)/$', products_by_tag, name='p-by-tag'),

    url(r'^$', ProductListView.as_view(), name="list"),
    
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),

    #url(r'category/list/$', category_list, name='category-list'),

    url(r'category/list/(?P<name>[\w-]+)/$', products_by_category, name='products-by-category'),
   
]

ecommerce/src/templates/base/css.html
{% load static %}


<!-- Bootstrap CSS -->
        
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<!--font awesome-->

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


<!-- jquery-confirm -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

ecommerce/src/templates/base/footer.html
{% load static %}

<footer class="py-3 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; ElectroBuy 2019</p>
    </div>
</footer>

ecommerce/src/templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        

        


        <!-- jQuery confirm -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

ecommerce/src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}



<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">
      <img src="https://getbootstrap.com/docs/4.3/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
      {% if brand_name %}<b>{{ brand_name}}</b>{% else %}eCommerce{% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url %}active{% endif %}">
          <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
        </li>
        <!-- <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
          <a class="nav-link" href="{{ contact_url }}">Contact</a>
        </li> -->
        
        <li class="nav-item {% if request.path == products_list_url %}active{% endif %}">
          <a class="nav-link" href="{{ products_list_url }}">Products</a>
        </li>

        

        <!-- {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
            <a class="nav-link" href="{{ logout_url }}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
            <a class="nav-link" href="{{ login_url }}">Login</a>
        </li>
        <li class="nav-item {% if request.path == register_url %}active{% endif %}">
            <a class="nav-link" href="{{ register_url }}">Register</a>
        </li>
        {% endif %}

        <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
            <a class="nav-link" href="{{ cart_url }}"><span class="navbar-cart-count">{{ request.session.cart_items }}</span> <i class="fas fa-shopping-cart"></i></a>
        </li> -->

        <!--
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
         -->
        
        </ul>




        <ul class="navbar-nav ml-auto">
          {% include 'search/snippets/search-form.html' %}

          {% if request.user.is_authenticated %}
          <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
              <a class="nav-link" href="{{ logout_url }}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item {% if request.path == login_url %}active{% endif %}">
              <a class="nav-link" href="{{ login_url }}">Login</a>
          </li>
          <li class="nav-item {% if request.path == register_url %}active{% endif %}">
              <a class="nav-link" href="{{ register_url }}">Register</a>
          </li>
          {% endif %}
  
          <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
              <a class="nav-link" href="{{ cart_url }}"><span class="navbar-cart-count">{{ request.session.cart_items }}</span> <i class="fas fa-shopping-cart"></i></a>
          </li>
          

        </ul>
    
    </div>
  </div>
  </nav>